name: Publish

on:
  workflow_dispatch:
  # schedule:
   # - cron: '0 10 * * *'
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: sudo apt-get install -y python3-paramiko python3-lxml
    - uses: actions/checkout@v3.6.0
      with:
        submodules: 'recursive'
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v3.2.0
      with:
        dotnet-version: 9.0.x
    - name: Install dependencies
      run: dotnet restore
    - name: Build Runner
      run: dotnet build Nebula.Runner --configuration Release
    - name: Build Launcher
      run: dotnet build Nebula.Launcher --configuration Release
    - name: Publish Launcher
      run: dotnet publish Nebula.Launcher --configuration Release -r win-x64 --output ./Release
    - name: ZIP Release
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r ./Release.zip ./Release
    - name: FTP Deploy Data
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./Release/
        server-dir: ./${{ github.sha }}/
    - name: FTP Deploy Release
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./Release.zip
        server-dir: ./Release.zip
