name: Publish launcher

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-launcher:
    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies
        run: sudo apt-get install -y python3-paramiko python3-lxml

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Create build
        run: ./publish_launcher.sh

      - name: Publish Release Assets
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          files: |
            ./publish/NebulaLauncher
            ./publish/NebulaLauncher.exe

  build-resolver:
    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies
        run: sudo apt-get install -y python3-paramiko python3-lxml

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Create build
        run: ./publish_update_resolver.sh

      - name: Publish Release Assets
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          files: |
            ./publish/NebulaUpdateResolver
            ./publish/NebulaUpdateResolver.exe